version: '3.8'
services:
  postgres:
    image: postgres:16-alpine # Légère et rapide
    container_name: ecommerce-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432" # Expose le port 5432 sur votre machine
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persiste les données
    restart: unless-stopped

volumes:
  postgres_data: