spring:
  application:
    name: ecommerce-backend
  
  # Configuration de la DataSource
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10 # Pool de connexions pour les hautes performances

  # Configuration JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: update # <<< Ici on met 'create' pour la première exécution, puis 'validate'
    show-sql: true # Affiche les requêtes SQL dans la console (utile pour debug)
    properties:
      hibernate:
        format_sql: true # Formatte les requêtes SQL pour les rendre lisibles
        dialect: org.hibernate.dialect.PostgreSQLDialect # Dialecte spécifique à Postgres

  # Sécurité (on désactive le filtre par défaut le temps de coder, sinon il bloque tout)
  #security:
    #user:
      #password: ignored # On override plus tard avec notre propre config

# Configuration pour Kafka 
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      # Clé : on utilise String
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Valeur : on utilise JSON (Spring va automatiquement gérer les Records)
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # Propriétés avancées pour éviter la perte de messages
      properties:
        # Indique à Kafka d'attendre que le leader ait écrit le message avant de répondre (acks=all)
        acks: all
        # Nombre de tentatives en cas d'échec réseau
        retries: 10
        # Permet d'écrire les messages en batch pour les performances
        batch.size: 16384
        # Désactive l'ajout d'en-têtes de type (compatible avec les consumers plus anciens)
        spring.json.add.type.headers: false
    consumer:
      group-id: ecommerce-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        # Indique au consommateur quels packages sont "sûrs" pour la désérialisation (sécurité)
        spring.json.trusted.packages: "*"
        # Permet de lire les messages depuis le début si on rejoint un nouveau groupe
        auto.offset.reset: earliest
    